version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:5.6.16
    volumes:
      - ./elasticsearch/scripts:/usr/share/elasticsearch/config/scripts
      - ./elasticsearch/synonym.txt:/usr/share/elasticsearch/config/synonym.txt
    # All of the ES settings can be set via the environment vars.
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
    ports:
      - "9200:9200"
    networks:
      swsapi:
        aliases:
          - elasticsearch

  api:
    build:
      # Point to the root of the project.
      context: ../../
      # This path is relative to the context.
      dockerfile: integration-tests/docker-sws-api/api/Dockerfile
    ports:
      - "5000:5000"
    networks:
      swsapi:
        aliases:
          - api
    depends_on:
      - elasticsearch

networks:
  swsapi:
